version: '3.8'

services:
  openscope-miner0:
    build: .
    environment:
      - MINER_PORT=8001
    ports:
      - "8001:8001"
    volumes:
      - ./env/openscope-miner0:/app/env

  # Add more miners as needed
